#!/bin/bash

prefix="$1"

if [[ -z $prefix ]]; then
    prefix="/usr/local/"
fi

mkdir -p "$prefix/bin" "$prefix/share/man/man1"
cp "shearch" "$prefix/bin/shearch"
cp "shearch.1" "$prefix/share/man/man1/shearch.1"
