#!/bin/bash
#
# Copyright (C) 2019,2022 Marios Tsolekas <marios.tsolekas@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


show_help() {
    cat <<EOH
Usage: shearch [OPTION]
GNU Find frontend using YAD

Available options are
  -h        print this message
  -d DIR    specify start directory for find. Default is $HOME
  -l N      limit the number of results. Default is 500
  -e        use locate instead of find. Take care to have an updated locate.db
  -s TERM   provide the search term here instead of prompting for it
  -v        print version
EOH
}

VERSION="1.1.0"
DIRECTORY="$HOME"
LIMIT=500
ENGINE="find"
TERM=""

EXE="${0##*/}"

while getopts ":vhed:l:s:" opt; do
    case $opt in
        h)
            show_help >&2
            exit 0
            ;;
        v)
            echo "$VERSION"
            exit 0
            ;;
        e)
            ENGINE="locate"
            ;;
        s)
            TERM="$OPTARG"
            ;;
        l)
            if ((OPTARG > 0)); then
                ((LIMIT = OPTARG))
            else
                echo "$EXE: option requires positive integer -- l" >&2
                exit 1
            fi
            ;;
        d)
            if [[ -d $OPTARG ]]; then
                DIRECTORY="$OPTARG"
            else
                echo "$EXE: directory does not exist -- d $OPTARG" >&2
                exit 1
            fi
            ;;
        :)
            echo "$EXE: option requires an argument -- $OPTARG" >&2
            exit 1
            ;;
        \?)
            echo "$EXE: illegal option -- $OPTARG" >&2
            exit 1
            ;;
    esac
done

shift "$((OPTIND - 1))"
if [[ -n $1 ]]; then
    echo "$EXE: too many arguments" >&2
    exit 1
fi

if [[ -z $TERM ]]; then
    TERM=$(yad --entry --title=Search)
    if [[ -z $TERM ]]; then
        exit 1
    fi
fi

if [[ $ENGINE = "find" ]]; then
    mapfile -t results < <(find "$DIRECTORY" -iname "*$TERM*" 2>/dev/null \
                               | head -n "$LIMIT" | sort -fg)
elif [[ $ENGINE = "locate" ]]; then
    mapfile -t results < <(locate -bi "*$TERM*" 2>/dev/null | grep "^$DIRECTORY*" \
                               | head -n "$LIMIT" | sort -fg)
fi

sel=$(yad --list --title=Search --width=600 --height=600 \
          --column=Path "${results[@]}" 2>/dev/null)
if [[ $sel =~ .*\|$ ]]; then
    sel=${sel::-1}
fi

if [[ -n $sel ]] && [[ -e $sel ]]; then
    xdg-open "$sel"
fi
